### ISSUE TITLE
Could we use the 'repo' functionality instead of a fork of spack?

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/spack#443]
Spack has a built-in way to handle having proprietary software:
https://spack.readthedocs.io/en/latest/repositories.html

For the BBP software, it seems like this would be a good fit

### Rationale
* Don't bleed internal packages to the rest of the world, can host it internally
* Easier to find the location of the packages, instead of having to navigate to `var/spack/repos/builtin/packages/` and then search within the list of all the other spack packages
* don't have to remember to pull from the `develop` branch
* won't be `This branch is 429 commits ahead, 1530 commits behind spack:develop.`

**Comment by mgeplf** [comment]
Couple other points:
* git on GPFS does not like working with such big repositories
* we are adding headers like:
```
##############################################################################
# Copyright (c) 2013-2018, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
```
To our internal packages, which is probably not required.

**Comment by matz-e** [comment]
Hm, so to me that raises the following questions:

* we have our own changes to Spack, you would still have to clone our "fork"
  * by having two repositories, chances that they will be out of sync increases — leads to different package views for users
  * upgrading dependencies / introducing new dependencies will require twice the PRs, handling of different repositories
* we could have a central Spack clone that users can use via modules, but:
  * how does this handle rebases?

Advantages would be
* it's easier to keep up with current spack
* clear distinction between in-house and external/open-sourced packages

> Couple other points:
> 
>     * git on GPFS does not like working with such big repositories

Could you elaborate? I don't have to many difficulties myself.

>     * we are adding headers like:
> 
> 
> ```
> ##############################################################################
> # Copyright (c) 2013-2018, Lawrence Livermore National Security, LLC.
> # Produced at the Lawrence Livermore National Laboratory.
> ```
>
> To our internal packages, which is probably not required.

Sure, we could just drop that even now. It's also part of Spack's auto-creation template. Does it hurt anything to have those present?



> * Don't bleed internal packages to the rest of the world, can host it internally
> 
> * Easier to find the location of the packages, instead of having to navigate to `var/spack/repos/builtin/packages/` and then search within the list of all the other spack packages

There's also `spack edit …`, which I tend to use, and then the use of `fzf`…

> * don't have to remember to pull from the `develop` branch

If you clone our repository, that should be unambiguous, shouldn't it? If you track branches, `git pull --rebase` doesn't need anyting.

> * won't be `This branch is 429 commits ahead, 1530 commits behind spack:develop.`

Doesn't seem such a big issue to me.

**Comment by mgeplf** [comment]
> we have our own changes to Spack, you would still have to clone our "fork"

I didn't know this - how big are the changes, and are there plans to upstream them?

> Could you elaborate? I don't have any difficulties myself.

Are you running it on GPFS on the viz cluster?
For on a clean repo, a `git status` takes almost 4 seconds:
```
$ /usr/bin/time git status
# On branch bglibpy_update
nothing to commit, working directory clean
0.02user 0.31system 0:03.44elapsed 9%CPU (0avgtext+0avgdata 8632maxresident)k
0inputs+0outputs (0major+2424minor)pagefaults 0swaps
```
I normally have a PS1 that tells me what the status is, but I have to turn it off when I go to work on spack.  Woe is me if I forget to do that, because sometimes it results in looooong delays.

> There's also spack edit …, which I tend to use, and then the use of fzf…

You have to know the package name for `spack edit`, and remember that `spack edit` exists.

> If you clone our repository, that should be unambiguous, shouldn't it?

When I make a branch and am done with it,  I'm in the habit of returning back to the `master` branch, and then I get confused, and then remember that I have to use `develop`.  This is probably because I'm not as active in packaging stuff.

> Doesn't seem such a big issue to me.

The main concern is that if a package isn't up to date or doesn't exist in our spack, one has to go check the upstream spack, and cherry pick the change if we don't want to cause merge problems down the road.  Also, it's hard to know which of the 429 commits have to do with in house software versus changes to spack itself (ie: my question from above).

**Comment by matz-e** [comment]
> > we have our own changes to Spack, you would still have to clone our "fork"
> 
> I didn't know this - how big are the changes, and are there plans to upstream them?

There are a handful of changes that we've made, most of which also have a PR pending upstream.

> > Could you elaborate? I don't have any difficulties myself.
> 
> Are you running it on GPFS on the viz cluster?
> For on a clean repo, a `git status` takes almost 4 seconds:
> 
> ```
> $ /usr/bin/time git status
> # On branch bglibpy_update
> nothing to commit, working directory clean
> 0.02user 0.31system 0:03.44elapsed 9%CPU (0avgtext+0avgdata 8632maxresident)k
> 0inputs+0outputs (0major+2424minor)pagefaults 0swaps
> ```
> 
> I normally have a PS1 that tells me what the status is, but I have to turn it off when I go to work on spack. Woe is me if I forget to do that, because sometimes it results in looooong delays.

I work on `bbpv?` almost exclusively, wasn't the viz cluster supposed to be decommissioned?

> > There's also spack edit …, which I tend to use, and then the use of fzf…
> 
> You have to know the package name for `spack edit`, and remember that `spack edit` exists.

True. We could already move our packages to a separate directory within the current repository, making this somewhat easier. There will still be potential for confusion, because one would have to discriminate between our open-source projects (which should live in the official repo and be submitted upstream), and our private stuff.

> > If you clone our repository, that should be unambiguous, shouldn't it?
> 
> When I make a branch and am done with it, I'm in the habit of returning back to the `master` branch, and then I get confused, and then remember that I have to use `develop`. This is probably because I'm not as active in packaging stuff.

You can set your local `master` to track our `develop` branch (I think `git checkout -b master -t origin/develop` or so). These are just labels (:

> > Doesn't seem such a big issue to me.
> 
> The main concern is that if a package isn't up to date or doesn't exist in our spack, one has to go check the upstream spack, and cherry pick the change if we don't want to cause merge problems down the road. Also, it's hard to know which of the 429 commits have to do with in house software versus changes to spack itself (ie: my question from above).

But will this not be present with split repositories, too? We want to deploy with a *somewhat stable* version, thus lagging behind the fast-moving original `develop`. If you chose to run with a current original `develop`, you will not be able to use the packages that we centrally deploy due to changing dependencies and thus hashes.



I don't really like the current situation, either, but I don't see a compelling other scenario that will make life consistently better.

**Comment by mgeplf** [comment]
> There are a handful of changes that we've made, most of which also have a PR pending upstream.

Are they required to build our packages?

> I work on bbpv? almost exclusively, wasn't the viz cluster supposed to be decommissioned?

Same.  Wasn't being clear, I'm still in the habit of calling the x86 machines in lugano the 'viz cluster', my bad.

> There will still be potential for confusion, because one would have to discriminate between our open-source projects (which should live in the official repo and be submitted upstream), and our private stuff.

How does this work now? IE: Should I have, for instance, created a PR in `spack/spack` for, say, libsonata, and then if/when it's accepted cherry pick it to `BlueBrain/spack`?  Or vica-versa?

> You can set your local master to track our develop branch

True.  Maybe I'm the only one who runs into this.

> But will this not be present with split repositories, too?

I'm not sure it would be: for one, we wouldn't be 'ahead' by anything; we'd just need to update our `BlueBrain/spack` fork to match the official repo periodically.  This would be our 'base' or 'stable' version.  I can see what you mean by having to juggle repositories though, that's a good point.

> We want to deploy with a somewhat stable version, thus lagging behind the fast-moving original develop.

What's our current way of having a 'stable version'?  I have read https://github.com/BlueBrain/spack/blob/develop/deploy/README.md and I'm not clear what the strategy is for having archived modules - I don't know where `DEPLOYMENT_ROOT` is, how to figure out what the spack checkout was that built it, etc..  I believe there was a discussion with Arseny about that, but I can't find it, maybe that makes it more clear.

> If you chose to run with a current original develop, you will not be able to use the packages that we centrally deploy due to changing dependencies and thus hashes.

Can you elaborate on this?  I think I'm missing a piece of the puzzle wrt 'hashes'.  Do you mean the hash embedded in the `package.py` or the `BlueBrain/spack` commit hash?

> Sure, we could just drop that even now. It's also part of Spack's auto-creation template. Does it hurt anything to have those present?

I missed responding to this from before.  I think that would be a question for the lawyers, but it seems strange to be assigning copyright to `2013-2018, Lawrence Livermore National Security, LLC.` to our internal software build.

**Comment by matz-e** [comment]
> > There will still be potential for confusion, because one would have to discriminate between our open-source projects (which should live in the official repo and be submitted upstream), and our private stuff.
> 
> How does this work now? IE: Should I have, for instance, created a PR in `spack/spack` for, say, libsonata, and then if/when it's accepted cherry pick it to `BlueBrain/spack`? Or vica-versa?

`libsonata` is official, so we would want it in `spack/spack`. But we would want to have it in a timely manner available for deployment, so a PR should be filed for both `BlueBrain/spack` and `spack/spack`. Then we would still have to periodically rebase our `BlueBrain/spack` on top of `spack/spack`, all the while dealing with `BlueBrain/spack-private` or so.

> > You can set your local master to track our develop branch
> 
> True. Maybe I'm the only one who runs into this.

Probably not. Should mention this somewhere in the docs.

> > We want to deploy with a somewhat stable version, thus lagging behind the fast-moving original develop.
> 
> What's our current way of having a 'stable version'? I have read https://github.com/BlueBrain/spack/blob/develop/deploy/README.md and I'm not clear what the strategy is for having archived modules - I don't know where `DEPLOYMENT_ROOT` is, how to figure out what the spack checkout was that built it, etc.. I believe there was a discussion with Arseny about that, but I can't find it, maybe that makes it more clear.

OK, that documentation was more for "internal" use between me and Pramod. Modules in the YYYY-MM directories are supposed to keep working, as we will not remove software from the installation path. We have a *stable* version by just sitting on top of `spack/spack` at the end of last year. We should really have a rebase and then keep the `spack/spack` version we're sitting on top consistent for another half year/year.

BTW, reproducibility is another can of worms. @pramodk would like it to be reproducible from source, and I agree on that. Keeping compiled software around seems easy to break (architectural change of hardware, different MPI configurations that screw execution). Maybe we should annotate modules with the actual hash of Spack used to create them/the software to be able to pinpoint the exact compilation configuration.

> > If you chose to run with a current original develop, you will not be able to use the packages that we centrally deploy due to changing dependencies and thus hashes.
> 
> Can you elaborate on this? I think I'm missing a piece of the puzzle wrt 'hashes'. Do you mean the hash embedded in the `package.py` or the `BlueBrain/spack` commit hash?

The hash of installed packages. For every package, a hash is created, containing hashes of the dependencies (recursively by construction). Say you just updated your `spack/spack`, and it's now 300 commits ahead of our deployment `BlueBrain/spack`. If you install software, one of the low-level dependencies may have changed it's hash due to updates, and this makes higher-level software 

> > Sure, we could just drop that even now. It's also part of Spack's auto-creation template. Does it hurt anything to have those present?
> 
> I missed responding to this from before. I think that would be a question for the lawyers, but it seems strange to be assigning copyright to `2013-2018, Lawrence Livermore National Security, LLC.` to our internal software build.

True. Feel free to delete that for our software. In general, I think it's handy to keep the template for packages we should push upstream.

**Comment by pramodk** [comment]
In addition to what has already been said, here is (my) summary:

> Could we use the 'repo' functionality

Yes. To me, `repo` here means separate `directory` under spack `repository`. This was already done for viz packages but we postponed it (to do it for all BBP packages together). `repo` could be separate `git repo` but see additional details below.

> instead of a fork of spack?

Possible but not practical. For production deployments like BB5, almost all spack based deployments today fork the repository and keep working on that. They sync with upstream time to time (every 3/6 months, which often full deployment from scratch). This is because how packages gets updated upstream and  spack re-concretise them for installation. We could discuss offline in detail.

Actually, historically we moved from repo model in separate git repository to what we have today. See [this] old BBP package specific repository.

> won't be This branch is 429 commits ahead, 1530 commits behind spack:develop.

Note that it's develop which moves quite fast. If you compare it with last stable release:
```
→ git log llnl/master..llnl/develop --pretty=oneline | wc -l
    1320
```

So, as Matthias said, we want to merge often with upstream but not too worried about those many changes.

If anyone sees issues with packages or relevant upstream changes (e.g. new features like `environments`), we can prioritise merge with upstream more often.

**Comment by mgeplf** [comment]
@matz-e 
> libsonata is official, so we would want it in spack/spack.

Hmm, I guess we'll have to create a strategy for this.  Are we maintaining any of software this way upstream?

> Maybe we should annotate modules with the actual hash of Spack used to create them/the software to be able to pinpoint the exact compilation configuration.

Yeah, I think that would be a good idea.
Does that mean there is currently no way to know what the exact 'concretization' was for the deployments under `...../jenkins/modules/applications/2019-0?` except by looking at the module file, and guess what which commit matches the time best?

> If you install software, one of the low-level dependencies may have changed it's hash due to updates, and this makes higher-level software

(is this sentence finished?)
Is the concern that lots of new software has to be rebuilt every time, and that we'll have many different versions on disk?

> True. Feel free to delete that for our software. In general, I think it's handy to keep the template for packages we should push upstream.

I don't know which software is ours, though, which makes this operation difficult.  This is one of the points of using the repo functionality.

@pramodk 
> Yes. To me, repo here means separate directory under spack repository.

I used the word `repo` specifically because that's the terminology used by spack, for example: `spack repo`  Can you point me to what you're planning with viz? Is it using the  `git submodule` functionality?

> For production deployments like BB5, almost all spack based deployments today fork the repository and keep working on that. 

Do they have proprietary software like we do?  Could you point me at some of these forks?

> Actually, historically we moved from repo model in separate git repository to what we have today. See [this] old BBP package specific repository.

> So, as Matthias said, we want to merge often with upstream but not too worried about those many changes.

Ok, makes sense.  I'm surprised that basically everything seems to be happening in the `develop` branch upstream as well - `master` (ie, a release?) hasn't happened in more than 6 months.

---

Another example of the monolithic spack repo coupled with the cluster giving long git operation times is a stash: 15 seconds to `git stash`, and 7 to `git stash pop`:
```
$ /usr/bin/time git stash
Saved working directory and index state WIP on bglibpy_update: a309894 updated bglibpy -> 2.0.28, updated psp-validation bglibpy dependency
HEAD is now at a309894 updated bglibpy -> 2.0.28, updated psp-validation bglibpy dependency

0.12user 1.06system 0:15.18elapsed 7%CPU (0avgtext+0avgdata 10392maxresident)k
0inputs+0outputs (0major+32098minor)pagefaults 0swaps

$ /usr/bin/time git stash pop
# On branch bglibpy_update
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   var/spack/repos/builtin/packages/psp-validation/package.py
#       modified:   var/spack/repos/builtin/packages/py-bglibpy/package.py
#
no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (a7839a9310260cb40e0852ee4b3ab84f7d19a326)

0.09user 0.58system 0:07.00elapsed 9%CPU (0avgtext+0avgdata 10968maxresident)k
0inputs+0outputs (0major+29415minor)pagefaults 0swaps
```

**Comment by matz-e** [comment]
> @matz-e
> 
> > libsonata is official, so we would want it in spack/spack.
> 
> Hmm, I guess we'll have to create a strategy for this. Are we maintaining any of software this way upstream?

I think HighFive is upstream, for example. I dropped behind a /little/ in syncing things.

> > Maybe we should annotate modules with the actual hash of Spack used to create them/the software to be able to pinpoint the exact compilation configuration.
> 
> Yeah, I think that would be a good idea.
> Does that mean there is currently no way to know what the exact 'concretization' was for the deployments under `...../jenkins/modules/applications/2019-0?` except by looking at the module file, and guess what which commit matches the time best?

Currently, the workflow would be as follows:

1. open module file
2. find directories used
3. directories contain version information and concretized specs in `.spack` in the installation tree (`${software}-${version}-${hash}` directory) - this will list all the options Spack used to compile software and dependency trees. I think it's just missing the Spack git commit hash itself? It also contains the `package.py` files…

IMO not that much different from `nix`. I'm very doubtful that exact binary reproducibility of software is possible, or that modules will be able to be re-used indefinitely. At CMS/Notre Dame, we had long discussions about this in our data preservation group… and it's very complicated. Just declaring modules to be there for eternity does not guarantee anything.
 
> > If you install software, one of the low-level dependencies may have changed it's hash due to updates, and this makes higher-level software
> 
> (is this sentence finished?)
> Is the concern that lots of new software has to be rebuilt every time, and that we'll have many different versions on disk?

Sorry, was a little over the place. Yes, excessive rebuilding and reusability are a concern. Especially given that the dependency tree for anything involving Python is quite large. Multiply this by number of users and frequency of recompilation…

> > True. Feel free to delete that for our software. In general, I think it's handy to keep the template for packages we should push upstream.
> 
> I don't know which software is ours, though, which makes this operation difficult. This is one of the points of using the repo functionality.
 
I think this is pretty minor. Just remove it when you come across it. If we open-source things and push them upstream, we'd have to add the headers again, anyway.

**Comment by mgeplf** [comment]
> I think HighFive is upstream, for example. I dropped behind a /little/ in syncing things.

Cool, no worries, I just wanted a sense for how it worked.

> directories contain version information and concretized specs in .spack

Ah, didn't know about that.  Helpful.

> I'm very doubtful that exact binary reproducibility of software is possible, or that modules will be able to be re-used indefinitely.

Yeah, that's been my conclusion as well.  However, a best effort and a series of bread crumbs can be helpful to figure out how something was compiled, and can make a huge difference.

> Yes, excessive rebuilding and reusability are a concern.

Ok.
---

I'm going to close this up, thanks for the responses.
Any changes that solve my two main friction points (improved the responsiveness of git and namespacing the bbp packages) would still be super helpful to me.  If you come up with a solution, that would be appreciated.

**Comment by wvangeit** [comment]
I think it might be useful to move this to jira so that we can keep looking at this issue. 
Personally I find this also a weird way of working for several reasons and I would find it much cleaner if the bbp packages are in a separate repo, e.g. because of:
- i think it would be better to keep in sync with the spack master
- we now have a massive amount of branches of this repo, i assume this has been pulled over from master ?
- cloning entire master repo might  become (already is?) problematic
